fragment Player on Player{
  id
  name
  hateLevel
  status
  imagePath
}

query GetAllPlayers {
  players: getAllPlayers {
    ...Player
  }
}

subscription OnPlayerUpdated {
  player: onPlayerUpdated {
    ...Player
  }
}

mutation UpdatePlayer($input: UpdatePlayerInput!) {
  updated: updatePlayer(input: $input) {
    ...Player
  }
}