fragment User on UserDTO {
  id
  player {
    hateLevel
    id
    name
    status
  }
  type
  userName 
}

mutation Login($password: String!, $username: String!) {
  user: login(password: $password, username: $username) {
    ...User 
  }
}