mutation Login($password: String!, $username: String!) {
  user: login(password: $password, username: $username) {
    user {
      id
      player {
        id
      }
      type
      userName
    }
  }
}