env: 'development'
Server:
  port: 4000
  graphqlPath: '/graphql'
  address: 'http://localhost:4000'
  jwtSecret: 'shhh'
Client:
  port: 3000
Auth:
  expHours: 2
  devAuthTokenHeader: 'X-Auth-Token'
DB:
  dbName: 'forgivingAppDB'
  connectionString: 'mongodb://localhost:27017'
  user: ''
  password: ''
  replicaSet:
    enabled: true
    setName: 'rs0'
    instances:
      - mongodb://localhost:27018
      - mongodb://localhost:27019
      - mongodb://localhost:27020
  